/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import { globby } from 'globby';

// const GAME_MECHANICS_FILES = await(['./docs/game-mechanics/**/*.mdx'])
// const PLAYER_RESOURCE_FILES = await(['./docs/player-resources/**/*.mdx'])
// const WORLD_INFORMATION_FILES = await(['./docs/world-information/**/*.mdx'])
//
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // gameSidebar: {
  //   'Game Mechanics A': GAME_MECHANICS_FILES,
  // },
  // playerSidebar: {
  //   'Player Resources B': PLAYER_RESOURCE_FILES,
  // },
  // loreSidebar:: {
  //   'Eclipse Phase Lore': WORLD_INFORMATION_FILES,
  // }

  gameSidebar: [{type: 'autogenerated', dirName: 'game-mechanics'}],

  playerSidebar: [{type: 'autogenerated', dirName: 'player-resources'}],

  loreSidebar: [{type: 'autogenerated', dirName: 'world-information'}]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
